FROM python:3.9-slim

WORKDIR /app
COPY . .
RUN apt update -y && apt install -y vim systemctl monit \
 && python -m pip install web.py \
 && pip install xmltodict \
 && pip install requests \
 && pip install xlsxwriter \
 && pip install --upgrade pip \
 && mv monitrc /etc/monit/monitrc \
 && chmod 0700 /etc/monit/monitrc \
 && systemctl enable monit \
 && systemctl start monit \
 && chmod +x entrypoint.sh

EXPOSE 8080 2812 80
ENTRYPOINT ["./entrypoint.sh"]
